server:
  port: 8803
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: han-admin
          uri: lb://han-admin
          predicates:
            - Path=/han-admin/**
          filters:
            - StripPrefix=1
        - id: han-demo
          uri: lb://han-demo
          predicates:
            - Path=/han-demo/**
          filters:
            - StripPrefix=1
        - id: han-auth
          uri: lb://han-auth
          predicates:
            - Path=/han-auth/**
          filters:
            - StripPrefix=1
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: 'http://localhost:8803/han-auth/rsa/publicKey' #配置RSA的公钥访问地址
  redis:
    database: 0
    port: 6379
    host: localhost
    password: 123456
secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/**/v2/api-docs"
      - "/**/*.js"
      - "/**/*.css"
      - "/**/*.png"
      - "/**/*.ico"
      - "/webjars/springfox-swagger-ui/**"
      - "/actuator/**"
      - "/han-auth/oauth/token"
      - "/han-auth/rsa/publicKey"
      - "/han-search/**"
      - "/han-portal/sso/login"
      - "/han-portal/sso/register"
      - "/han-portal/sso/getAuthCode"
      - "/han-portal/home/**"
      - "/han-portal/product/**"
      - "/han-portal/brand/**"
      - "/han-admin/admin/login"
      - "/han-admin/admin/register"
      - "/han-admin/minio/upload"
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
