server:
  port: 9999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/han?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*Mapper.xml
  global-config:
    # 逻辑删除配置
    db-config:
      # 删除前
      logic-not-delete-value: 1
      # 删除后
      logic-delete-value: 0
#  config-location: classpath:mybatis-config.xml
logging:
  level:
    com:
      alibaba:
        nacos:
          client:
            naming: warn